[package]
name = "lemmy-help"
description = "Emmylua parser and transformer"
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = { version = "0.8.0", default-features = false }
clap = { version = "3.1.10", default-features = false, features = ["std", "derive", "cargo"] }
tabled = { version = "0.6.1", default-features = false  }

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 's'
panic = 'abort'
